# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test BBoxSuggestion

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r official/requirements.txt
        pip install pytest
        pip install boto3
        sudo apt-get update
        sudo apt-get install -y git
        git clone https://github.com/tensorflow/models.git
        cd models/research
        pip install --user -r official/requirements.txt
        pip install tensorflow==2.15.0 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::026823144273:role/github_actions_matsutake
        aws-region: ap-northeast-1
    - name: Test with pytest
      run: |
        pytest s3/*_test.py
        pytest *_test.py
